name: Django CI-Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python-tests:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          super_secret: ${{ secrets.SECRET_KEY }}
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/linux.txt
          python project/manage.py test
